import {Rule} from '@sanity/types'

export const Course =  {
    name:"course",
    title:"Course",
    type:"document",
    fields:[
        {
            name:"name",
            title:"Name",
            type:"string"
        },
        {
            name:"slug",
            title:"Slug",
            type:"slug",
            options:{
                source:"name",
                maxLength:90
            }
        },
        {
            name:"title",
            title:"Title",
            type:"string",
        },
        {
            name:"description",
            title:"Description",
            type:"array",
            of:[{type:"block"}]
        },
        {
            name:"price",
            title:"Price",
            type:"string",
        },
        {
            name:"image",
            title:"Image",
            type:"image"
        },
        {
            name:"category",
            title:"Category",
            type:"reference",
            to:[{type:"category"}]
        },
        {
            name:"startDate",
            title:"StartDate",
            type:"date"
        },
        {
            name:"classTime",
            title:"ClassTime",
            type:"string"
        },
        {
            name:"classLocation",
            title:"ClassLocation",
            type:"string"
        },
        {
            name:"lectures",
            title:"Lectures",
            type:"number",
            validation: (Rule:Rule) => Rule.min(1),
            initialValue: 1
        },
        {
            name:"duration",
            title:"Duration",
            type:"string",
        },
        {
            name:"quizzes",
            title:"Quizzes",
            type:"number",
            validation:(Rule:Rule) => Rule.min(1)
        },
        {
            name:"teacher",
            title:"Teacher",
            type:"reference",
            to:[{type:"teacher"}]
        },
        {
            name:"onWindow",
            title:"onWindow",
            type:"boolean"
        }
    ]
}