import {Rule} from '@sanity/types'

export const Footer = {
    name:"footer",
    title:"Lábléc",
    type:"document",
    fields:[
        {
            name:"groups",
            title:"Csoportok",
            type:"array",
            of:[{type:"footerGroup"}],
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"telephone",
            title:"Telefon",
            type:"string",
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"mobilephone",
            title:"Mobiltelefon",
            type:"string"
        },
        {
            name:"address",
            title:"Cím",
            type:"string",
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"email",
            title:"Email",
            type:"string",
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"wechat",
            title:"Wechat",
            type:"image",
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"tiktok",
            title:"Tiktok",
            type:'url',
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"xiaohongshu",
            title:"Xiaohongshu",
            type:'url',
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"facebook",
            title:"Facebook",
            type:"url",
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"instagram",
            title:"Instagram",
            type:"url",
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"youtube",
            title:"Youtube",
            type:"url",
            validation:(Rule:Rule)=>Rule.required()
        },
        {
            name:"description",
            title:"Leírás",
            type:"internationalizedArrayString",
            validation:(Rule:Rule)=>Rule.required()
        }
    ]
}