export const Footer = {
    name:"footer",
    title:"Footer",
    type:"document",
    fields:[
        {
            name:"groups",
            title:"Groups",
            type:"array",
            of:[{type:"footerGroup"}]
        },
        {
            name:"telephone",
            title:"Telephone",
            type:"string"
        },
        {
            name:"mobilephone",
            title:"Mobilephone",
            type:"string"
        },
        {
            name:"address",
            title:"Address",
            type:"string"
        },
        {
            name:"wechat",
            title:"Wechat",
            type:"image"
        },
        {
            name:"twitter",
            title:"Twitter",
            type:'url'
        },
        {
            name:"facebook",
            title:"Facebook",
            type:"url"
        },
        {
            name:"instagram",
            title:"Instagram",
            type:"url"
        },
        {
            name:"youtube",
            title:"Youtube",
            type:"url"
        },
        {
            name:"description",
            title:"Description",
            type:"string"
        }
    ]
}