export const Footer = {
    name:"footer",
    title:"Lábléc",
    type:"document",
    fields:[
        {
            name:"groups",
            title:"Csoportok",
            type:"array",
            of:[{type:"footerGroup"}]
        },
        {
            name:"telephone",
            title:"Telefon",
            type:"string"
        },
        {
            name:"mobilephone",
            title:"Mobiltelefon",
            type:"string"
        },
        {
            name:"address",
            title:"Cím",
            type:"string"
        },
        {
            name:"email",
            title:"Email",
            type:"string"
        },
        {
            name:"wechat",
            title:"Wechat",
            type:"image"
        },
        {
            name:"twitter",
            title:"Twitter",
            type:'url'
        },
        {
            name:"facebook",
            title:"Facebook",
            type:"url"
        },
        {
            name:"instagram",
            title:"Instagram",
            type:"url"
        },
        {
            name:"youtube",
            title:"Youtube",
            type:"url"
        },
        {
            name:"description",
            title:"Leírás",
            type:"string"
        }
    ]
}