export const Registration = {
    name:"registration",
    title:"Bejegyzés",
    type:"document",
    fields:[
        {
            name:"name",
            title:"Név",
            type:"string",
        },
        {
            name:"email",
            title:"Email",
            type:"string",
        },
        {
            name:"message",
            title:"Üzenet",
            type:"string",
        },
        {
            name:"type",
            title:"Típus",
            type:"string",
        },
        {
            name:"activityName",
            title:"Tevékenységnév",
            type:"string",
        },
        {
            name:"startDate",
            title:"Kezdő dátum",
            type:"string"
        }
    ]
}