export const Testimonial = {
  name:"testimonial",
  title:"Ajánlólevél",
  type:"document",
  fields:[
    {
      name:"name",
      title:"Név",
      type:"string"
    },
    {
      name:"content",
      title:"Tartalom",
      type:"array",
      of:[{type:"block"}]
    },
    {
      name:"image",
      title:"Kép",
      type:"image",
      options:{
        hotspot:true
      }
    }
  ]
}